import sys
import os

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from rag import JavaTutorRAG

def parse_labs_file(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        labs = []
        current_lab = {}
        for line in file:
            line = line.strip()
            if line.startswith('Lab '):
                if current_lab:
                    if 'incorrect_solution' not in current_lab:
                        current_lab['incorrect_solution'] = []
                    labs.append(current_lab)
                    current_lab = {}
                current_lab['name'] = line.split(':')[0]
            elif line.startswith('Incorrect Solution:'):
                current_lab['incorrect_solution'] = []
            elif current_lab.get('incorrect_solution') is not None:
                current_lab['incorrect_solution'].append(line)
        if current_lab:
            if 'incorrect_solution' not in current_lab:
                current_lab['incorrect_solution'] = []
            labs.append(current_lab)
    return labs

def generate_prompts(labs):
    prompts = []
    for lab in labs:
        lab_name = lab.get('name', 'Unknown Lab')
        incorrect_solution = '\n'.join(lab.get('incorrect_solution', []))
        
        prompts.append({
            "title": f"Plan: {lab_name}",
            "prompt": f"Provide a high-level plan for solving the '{lab_name}' lab."
        })
        prompts.append({
            "title": f"Pseudocode: {lab_name}",
            "prompt": f"Write pseudocode for the '{lab_name}' lab."
        })
        prompts.append({
            "title": f"Debug: {lab_name}",
            "prompt": f"Given the following incorrect solution for the '{lab_name}' lab, identify and fix the errors:\n\n{incorrect_solution}"
        })
    return prompts

def main():
    current_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(current_dir)
    data_dir = os.path.join(project_root, "data")
    results_dir = os.path.join(project_root, "results")
    input_file = os.path.join(data_dir, "input.txt")
    output_file = os.path.join(results_dir, "evaluation.md")

    if not os.path.exists(input_file):
        print(f"Error: Input file (input.txt) not found in {data_dir}")
        return

    print("Initializing RAG Engine...")
    tutor = JavaTutorRAG(data_dir=data_dir)

    print(f"Parsing inputs from {input_file}...")
    labs = parse_labs_file(input_file)
    tasks = generate_prompts(labs)

    print(f"Starting batch evaluation. Output will be saved to {output_file}")
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("# Java Tutor Evaluation Report\n\n")
        f.write("Generated by `src/evaluator.py` using `llama3`.\n\n")
        for i, task in enumerate(tasks):
            print(f"Processing ({i+1}/{len(tasks)}): {task['title']}")
            
            answer = tutor.query(task['prompt'])
            
            f.write(f"## {task['title']}\n\n")
            f.write(f"**Prompt**: {task['prompt'].splitlines()[0]}...\n\n")
            f.write(f"{answer}\n\n")
            f.write("---\n\n")
            f.flush()

    print("Evaluation Complete!")

if __name__ == "__main__":
    main()
